# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    #nixos-hardware.nixosModules.lenovo-thinkpad-t14-amd-gen1
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c772918e-3832-45ae-8c97-05b3d837ed8b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5DF2-A721";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  boot = {
    initrd = {
      #The set of kernel modules in the initial ramdisk used during the boot process.
      availableKernelModules = [
        "nvme"
        "ehci_pci"
        "xhci_pci"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];

      luks.devices."luks-3b194756-e29b-425a-b088-0a0468840011" = {
        device = "/dev/disk/by-uuid/3b194756-e29b-425a-b088-0a0468840011";
        allowDiscards = true;
      };
    };

    #kernelPackages = pkgs.linuxPackages_latest;
    kernelPackages = pkgs.linuxPackages_zen;

    #extraModulePackages = [];

    #The set of kernel modules to be loaded in the second stage of the boot process.
    kernelModules = ["kvm-amd"];
    kernelParams = ["amd_pstate=active" "usbcore.autosuspend=-1"];

    #blacklistedKernelModules = [ "acpi-cpufreq" ];
  };

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  #services.auto-epp.enable = true;

  powerManagement = {
    enable = true;
    powertop.enable = true;
  };

  services.tlp = {
    enable = true;
    settings = {
      TLP_DEFAULT_MODE = "BAT";
      TLP_PERSISTENT_DEFAULT = 1;
    };
  };
}
